# Generated by Django 3.2.3 on 2021-05-29 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='favourites',
            field=models.ManyToManyField(db_table='photo_users', null=True, related_name='fav_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
