# Generated by Django 3.2.3 on 2021-05-29 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0004_alter_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favourites',
            field=models.ManyToManyField(blank=True, db_table='album_users', null=True, related_name='fav_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
