# Generated by Django 3.2.3 on 2021-05-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_album_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='token',
            field=models.UUIDField(blank=True, null=True, verbose_name='Токен'),
        ),
    ]
